// NSW (Sydney + NSW) traffic cameras - pre-built from the Transport for NSW Live Traffic feed
// (https://data.livetraffic.com/cameras/traffic-cam.json). Generated 2026-06-14. 197 cameras.
// Feed has no CORS, so it is baked like nyc-cams.js. window.NSW_CAMS = [[name, lat, lon, imageUrl], ...]
window.NSW_CAMS = [
  ['5 Ways (Miranda) · SYD SOUTH', -34.02977, 151.10533, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/5_ways_miranda.jpeg'],
  ['Airport Drive (Mascot) · SYD MET', -33.933667, 151.161891, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/airport_dr_mascot.jpeg'],
  ['Alison Road (Randwick) · SYD MET', -33.90641, 151.23122, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/alison_road_randwick.jpeg'],
  ['Anzac Bridge (Eastbound) · SYD MET', -33.86789, 151.18022, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/anzac_bridge_eastbound.jpeg'],
  ['Anzac Bridge (Westbound) · SYD MET', -33.869692, 151.188029, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/anzac_bridge_westbound.jpeg'],
  ['Anzac Parade (Kensington) · SYD MET', -33.907296, 151.223699, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/anzac_parade_kensington.jpeg'],
  ['Anzac Parade (Kingsford) · SYD MET', -33.923886, 151.227638, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/anzac_parade_kingsford.jpeg'],
  ['Anzac Parade (Moore Park) · SYD MET', -33.89534, 151.22151, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/anzac_parade_moore_park.jpeg'],
  ['Audley Road (Audley Weir) · SYD SOUTH', -34.073084, 151.056689, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/audley_road_audley_weir.jpeg'],
  ['Audley Weir (East) · SYD SOUTH', -34.0735779, 151.057465, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/audley_weir_east.jpeg'],
  ['Audley Weir (South) · SYD SOUTH', -34.073741, 151.05747, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/audley_weir_south.jpeg'],
  ['Chifley Road (Bell) · REG WEST', -33.511658, 150.280817, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/chifley_road_bell.jpeg'],
  ['Bexley Road (Bexley North) · SYD SOUTH', -33.936532, 151.112287, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/bexley_rd_bexley_north.jpeg'],
  ['Botany Road (Matraville) · SYD MET', -33.967214, 151.230727, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/botany_rd_matraville.jpeg'],
  ['Bunnerong Road (Matraville) · SYD MET', -33.966895, 151.231128, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/bunnerong_rd_matraville.jpeg'],
  ['Burnt Bridge Creek (Balgowlah) · SYD NORTH', -33.788582, 151.265661, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/burnt_bridge_creek_balgowlah.jpeg'],
  ['Camden Bypass (Narellan) · SYD WEST', -34.045534, 150.743807, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/camden_bypass_narellan.jpeg'],
  ['Campbell Rd and Euston Rd, St Peters · SYD MET', -33.915336, 151.184491, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/campbell_rd_and_euston_rd_st_peters.jpeg'],
  ['Carlingford Road (Epping) · SYD NORTH', -33.770871, 151.080881, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/carlingford_road_epping.jpeg'],
  ['City Road (Newtown) · SYD MET', -33.890699, 151.188925, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/city_road_newtown.jpeg'],
  ['City West Link · SYD MET', -33.87175, 151.171829, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/city_west_link.jpeg'],
  ['City West Link (Lilyfield) · SYD MET', -33.8726349, 151.170212, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/city_west_link_lilyfield.jpeg'],
  ['Cleveland Street (Surry Hills) · SYD MET', -33.891569, 151.212861, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/cleveland_street_surry_hills.jpeg'],
  ['Cumberland Highway (Carlingford) · SYD NORTH', -33.77967, 151.05237, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/cumberland_highway_carlingford.jpeg'],
  ['Cumberland Highway (Merrylands) · SYD WEST', -33.83031, 150.96039, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/cumberland_highway_merrylands.jpeg'],
  ['Eastern Distributor (Woolloomooloo) · SYD MET', -33.865977, 151.213658, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/eastern_distributor_woolloomooloo.jpeg'],
  ['Eastern Distributor (Zetland) · SYD MET', -33.90964, 151.21303, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/eastern_distributor_zetland.jpeg'],
  ['Echuca-Moama Bridge (Moama) · REG SOUTH', -36.112127, 144.74397, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/echuca-moama_bridge_moama.jpeg'],
  ['Epping Road (Lane Cove) · SYD NORTH', -33.810643, 151.163759, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/epping_road_lane_cove.jpeg'],
  ['Epping Road (Macquarie Park) · SYD NORTH', -33.7777061, 151.108337, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/epping_road_macquarie_park.jpeg'],
  ['Erskine Street (Sydney) · SYD MET', -33.866579, 151.205779, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/erskine_st_sydney.jpeg'],
  ['Falcon Street (Crows Nest) · SYD NORTH', -33.82768, 151.20084, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/falcon_street_crows_nest.jpeg'],
  ['Five Islands Road (Port Kembla) · REG SOUTH', -34.465594, 150.871564, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/five_islands_road_port_kembla.jpeg'],
  ['Foreshore Road (Banksmeadow) · SYD MET', -33.961818, 151.214619, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/foreshore_road_banksmeadow.jpeg'],
  ['General Holmes Drive (Botany) · SYD MET', -33.94447, 151.18805, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/general_holmes_drive_botany.jpeg'],
  ['George St (Railway Square) · SYD MET', -33.88291, 151.2041, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/george_st_railway_square.jpeg'],
  ['Giinagay Way (Macksville) · REG NORTH', -30.70743, 152.920825, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/giinagay_way_macksville.jpeg'],
  ['Gladesville Bridge (Drummoyne) · SYD MET', -33.84772, 151.151947, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/gladesville_bridge_drummoyne.jpeg'],
  ['Gore Hill Freeway (Artarmon) · SYD NORTH', -33.817233, 151.201508, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/gore_hill_freeway_artarmon.jpeg'],
  ['Goulburn Street (Sydney) · SYD MET', -33.877991, 151.207124, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/goulburn_street_sydney.jpeg'],
  ['Great Western Highway (Bathurst) · REG WEST', -33.418282, 149.591139, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/great_western_highway_bathurst.jpeg'],
  ['Great Western Highway (Hazelbrook) · REG WEST', -33.720882, 150.451611, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/great_western_highway_hazelbrook.jpeg'],
  ['Great Western Highway (Katoomba) · REG WEST', -33.710785, 150.311042, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/great_western_highway_katoomba.jpeg'],
  ['Great Western Highway at Station Street · REG WEST', -33.5906525, 150.254852, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/great_western_highway_mount_victoria.jpeg'],
  ['Great Western Highway (Victoria Pass) · REG WEST', -33.582099, 150.2315, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/great_western_highway_victoria_pass.jpeg'],
  ['Harris Street (Ultimo) · SYD MET', -33.8777351, 151.198624, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/harris_st_ultimo.jpeg'],
  ['Homebush Bay Drive (Homebush) · SYD MET', -33.85429, 151.076989, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/homebush_bay_drive_homebush.jpeg'],
  ['Hume Highway (Ashfield) · SYD MET', -33.88851, 151.1174, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/hume_highway_ashfield.jpeg'],
  ['Hume Highway (Bankstown) · SYD SOUTH', -33.90583, 151.04048, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/hume_highway_bankstown.jpeg'],
  ['Hume Highway (Strathfield) · SYD MET', -33.886, 151.0681, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/hume_highway_strathfield.jpeg'],
  ['Hume Highway (Villawood) · SYD SOUTH', -33.88951, 150.97311, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/hume_highway_villawood.jpeg'],
  ['Hume Highway (Cumberland Highway, Liverpool) · SYD SOUTH', -33.91519, 150.92073, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/hume_highway_cumberland_highway_liverpool.jpeg'],
  ['Hume Highway (Elizabeth Drive, Liverpool) · SYD SOUTH', -33.91941, 150.919356, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/hume_highway_elizabeth_drive_liverpool.jpeg'],
  ['Hume Motorway (Campbelltown) · SYD SOUTH', -34.06199, 150.785324, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/hume_motorway_campbelltown.jpeg'],
  ['Hume Motorway (St Andrews) · SYD SOUTH', -34.02971, 150.82399, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/hume_motorway_st_andrews.jpeg'],
  ['Hunter Expressway (Buchanan) · REG NORTH', -32.829628, 151.529816, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/hunter_expressway_buchanan.jpeg'],
  ['Hunter Expressway and Lovedale Road · REG NORTH', -32.723488, 151.403663, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/hunter_expressway_and_lovedale_rd.jpeg'],
  ['Hunter Expressway and Wine Country Dr · REG NORTH', -32.668371, 151.361121, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/hunter_expressway_and_wine_country_dr.jpeg'],
  ['James Ruse Drive (Rosehill) · SYD WEST', -33.81927, 151.02188, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/james_ruse_drive_rosehill.jpeg'],
  ['Jenolan Caves Road (Hampton) · REG WEST', -33.676847, 150.050886, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/jenolan_caves_road_hampton.jpeg'],
  ['Kent Street (Sydney) · SYD MET', -33.87422, 151.205249, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/kent_street_sydney.jpeg'],
  ['King Georges Road (Beverly Hills) · SYD SOUTH', -33.952393, 151.083523, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/king_georges_road_beverly_hills.jpeg'],
  ['King Georges Road (Hurstville) · SYD SOUTH', -33.965706, 151.094488, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/king_georges_road_hurstville.jpeg'],
  ['King St & Sussex St (Sydney) · SYD MET', -33.868728, 151.203629, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/king_st_&_sussex_st_sydney.jpeg'],
  ['Kosciuszko Rd & Alpine Way (Jindabyne) · REG SOUTH', -36.410484, 148.595367, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/kosciuszko_rd_&_alpine_way_jindabyne.jpeg'],
  ['Kosciuszko Rd and Perisher Valley (Kosciuszko National Park) · REG SOUTH', -36.404743, 148.413284, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/kosciuszko_rd_&_perisher_valley_kosciuszko_national_park.jpeg'],
  ['Kosciuszko Road (Wilsons Valley) · REG SOUTH', -36.350024, 148.522067, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/kosciuszko_road_wilsons_valley.jpeg'],
  ['Lower Portland Ferry (East) · SYD WEST', -33.438217, 150.885748, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/lower_portland_ferry_east.jpeg'],
  ['Lower Portland Ferry (West) · SYD WEST', -33.438139, 150.885556, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/lower_portland_ferry_west.jpeg'],
  ['M1 Pacific Motorway (Hawkesbury River) · REG NORTH', -33.53074, 151.20082, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m1_pacific_motorway_hawkesbury_river.jpeg'],
  ['M1 Pacific Motorway (Hunter Expressway) · REG NORTH', -32.88914, 151.6014, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m1_pacific_motorway_hunter_expressway.jpeg'],
  ['M1 Pacific Motorway (John Renshaw Drive) · REG NORTH', -32.8134, 151.635833, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m1_pacific_motorway_john_renshaw_drive.jpeg'],
  ['M1 Pacific Motorway (Kariong) · REG NORTH', -33.4184, 151.294159, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m1_pacific_motorway_kariong.jpeg'],
  ['M1 Pacific Motorway (Mount White) · REG NORTH', -33.45451, 151.205948, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m1_pacific_motorway_mount_white.jpeg'],
  ['M1 Pacific Motorway (Ourimbah) · REG NORTH', -33.34475, 151.369064, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m1_pacific_motorway_ourimbah.jpeg'],
  ['M1 Pacific Motorway (Sparks Road) · REG NORTH', -33.2286453, 151.422409, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m1_pacific_motorway_sparks_road.jpeg'],
  ['M1 Pacific Motorway (Wahroonga) · REG NORTH', -33.71873, 151.10991, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m1_pacific_motorway_wahroonga.jpeg'],
  ['M1 Pacific Motorway (Windy Banks) · REG NORTH', -33.63605, 151.147751, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m1_pacific_motorway_windy_banks.jpeg'],
  ['M1 Pacific Motorway (Mt Colah North) · REG NORTH', -33.6620636, 151.127029, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m1_pacific_mwy_mt_colah_north.jpeg'],
  ['M1 Princes Motorway (Mt Ousley) · REG SOUTH', -34.39078, 150.858024, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m1_princes_motorway_mt_ousley.jpeg'],
  ['M2 (Pennant Hills) · SYD NORTH', -33.75906, 151.04926, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m2_pennant_hills.jpeg'],
  ['M2 (Ryde) · SYD NORTH', -33.78199, 151.13159, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m2_ryde.jpeg'],
  ['M4 Western Motorway (Prospect) · SYD WEST', -33.80546, 150.91589, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m4_prospect_-_temporarily_decommissioned_by_prospect_hwy_upgrade_project.jpeg'],
  ['M4 Western Motorway (Auburn) · SYD WEST', -33.838697, 151.035992, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m4_western_motorway_auburn.jpeg'],
  ['M4 Western Motorway (Emu Plains) · SYD WEST', -33.762952, 150.657907, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m4_western_motorway_emu_plains.jpeg'],
  ['M4 Western Motorway (South Wentworthville) · SYD WEST', -33.81629, 150.963639, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m4_western_motorway_south_wentworthville.jpeg'],
  ['M4 Western Motorway (Minchinbury) · SYD WEST', -33.79519, 150.84489, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m4_western_motorway_minchinbury.jpeg'],
  ['M4 Western Motorway (Olympic Park) · SYD MET', -33.85557, 151.06433, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m4_western_motorway_olympic_park.jpeg'],
  ['M4 Western Motorway (St Marys) · SYD WEST', -33.78512, 150.77086, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m4_western_motorway_st_marys.jpeg'],
  ['M5 (Kingsgrove) · SYD MET', -33.937089, 151.103865, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m5_kingsgrove.jpeg'],
  ['M5 (Liverpool) · SYD SOUTH', -33.93819, 150.9135, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m5_liverpool.jpeg'],
  ['M5 (Milperra) · SYD SOUTH', -33.94493, 150.98242, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m5_milperra.jpeg'],
  ['M5 (Padstow) · SYD SOUTH', -33.940298, 151.035648, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m5_padstow.jpeg'],
  ['M5 East (Beverly Hills) · SYD MET', -33.94291, 151.0769, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m5_east_beverly_hills.jpeg'],
  ['M5 / M7 · SYD SOUTH', -33.956944, 150.876646, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m5_m7_camden_valley.jpeg'],
  ['M7 (Glenwood) · SYD WEST', -33.73796, 150.91777, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m7_glenwood.jpeg'],
  ['M7 at The Horsley Drive (Horsley Park) · SYD WEST', -33.84171, 150.85556, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m7_at_the_horsley_drive_horsley_park.jpeg'],
  ['Macquarie Street (Sydney) · SYD MET', -33.865804, 151.212496, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/macquarie_street_sydney.jpeg'],
  ['Manly Road (Seaforth) · SYD NORTH', -33.8017, 151.24631, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/manly_road_seaforth.jpeg'],
  ['Marsh St (Mascot) · SYD MET', -33.933574, 151.162779, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/marsh_st_mascot.jpeg'],
  ['Marsh Street (Arncliffe) · SYD MET', -33.938402, 151.151576, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/marsh_street_arncliffe.jpeg'],
  ['Memorial Drive (Towradgi) · REG SOUTH', -34.383533, 150.900312, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/memorial_drive_towradgi.jpeg'],
  ['Menangle Road (Menangle Park) · SYD SOUTH', -34.117413, 150.740491, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/menangle_road_menangle_park.jpeg'],
  ['Military Road (Neutral Bay) · SYD NORTH', -33.8315, 151.22231, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/military_road_neutral_bay.jpeg'],
  ['Milperra Road (Ashford Avenue) · SYD WEST', -33.929952, 150.990865, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/milperra_road_ashford_avenue.jpeg'],
  ['Milperra Road (Henry Lawson Dr) · SYD WEST', -33.929607, 150.980317, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/milperra_road_henry_lawson_dr.jpeg'],
  ['Mortlake Ferry (North) · SYD MET', -33.837362, 151.105798, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/mortlake_ferry_north.jpeg'],
  ['Mortlake Ferry (South) · SYD MET', -33.837481, 151.105613, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/mortlake_ferry_south.jpeg'],
  ['Narellan Road (Campbelltown) · SYD SOUTH', -34.067885, 150.802497, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/narellan_road_campbelltown.jpeg'],
  ['New England Highway (Hexham) · REG NORTH', -32.821351, 151.682176, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/new_england_highway_hexham.jpeg'],
  ['New Illawarra Road (Bangor Bypass) · SYD SOUTH', -34.023547, 151.007751, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/new_illawarra_road_bangor_bypass.jpeg'],
  ['New South Head Road (Edgecliff) · SYD MET', -33.876651, 151.231838, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/new_south_head_road_edgecliff.jpeg'],
  ['Newcastle Road (Newcastle) · REG NORTH', -32.9044, 151.687725, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/newcastle_rd_and_crest_rd_wallsend.jpeg'],
  ['Old South Head Road (Bondi Junction) · SYD MET', -33.8909721, 151.253418, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/old_south_head_road_bondi_junction.jpeg'],
  ['Old Windsor Road (Beaumont Hills) · SYD WEST', -33.70421, 150.93016, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/old_windsor_road_beaumont_hills.jpeg'],
  ['Old Windsor Road (Winston Hills) · SYD WEST', -33.76579, 150.95857, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/old_windsor_road_winston_hills.jpeg'],
  ['ORiordan Street (Mascot) · SYD MET', -33.930637, 151.186461, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/oriordan_street_mascot.jpeg'],
  ['Oxford St and Young St · SYD MET', -33.88485, 151.224915, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/oxford_st_and_young_st_sydney.jpeg'],
  ['Pacific Highway (Chatswood) · SYD NORTH', -33.79836, 151.17851, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/pacific_highway_chatswood.jpeg'],
  ['Pacific Highway (Doyalson) · REG NORTH', -33.20578, 151.51643, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/pacific_highway_doyalson.jpeg'],
  ['Pacific Highway (Macksville) · REG NORTH', -30.7046185, 152.9386, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/pacific_highway_macksville.jpeg'],
  ['Pacific Highway (Tomago) · REG NORTH', -32.809658, 151.709905, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/pacific_highway_tomago.jpeg'],
  ['Parramatta Road (Ashfield) · SYD MET', -33.886095, 151.138868, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/parramatta_road_ashfield.jpeg'],
  ['Parramatta Road (Camperdown) · SYD MET', -33.884899, 151.185435, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/parramatta_road_camperdown.jpeg'],
  ['Parramatta Road (Leichhardt) · SYD MET', -33.88904, 151.15317, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/parramatta_road_leichhardt.jpeg'],
  ['Parramatta Road (Parramatta) · SYD WEST', -33.82758, 151.00475, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/parramatta_road_parramatta.jpeg'],
  ['Parramatta Road (Silverwater) · SYD MET', -33.84504, 151.0422, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/parramatta_road_silverwater.jpeg'],
  ['Parramatta Road (Strathfield) · SYD MET', -33.86652, 151.09364, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/parramatta_road_strathfield.jpeg'],
  ['Pennant Hills Road (Beecroft) · SYD NORTH', -33.740195, 151.064007, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/pennant_hills_road_beecroft.jpeg'],
  ['Pennant Hills Road (Thornleigh) · SYD NORTH', -33.730807, 151.081401, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/pennant_hills_road_thornleigh.jpeg'],
  ['Pittwater Road (Narrabeen) · SYD NORTH', -33.70989, 151.29582, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/pittwater_road_narrabeen.jpeg'],
  ['Princes Highway (Batemans Bay) · REG SOUTH', -35.70812, 150.174801, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_highway_batemans_bay.jpeg'],
  ['Princes Highway (Blakehurst) · SYD MET', -33.98789, 151.11166, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_highway_blakehurst.jpeg'],
  ['Princes Highway (Bulli) · REG SOUTH', -34.329975616231316, 150.91393517568778, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_highway_bulli.jpeg'],
  ['Princes Highway (Heathcote) · SYD SOUTH', -34.079598, 151.010562, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_highway_heathcote.jpeg'],
  ['Princes Highway (Kogarah) · SYD MET', -33.96433, 151.13719, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_highway_kogarah.jpeg'],
  ['Princes Highway (St Peters N) · SYD MET', -33.9156, 151.17467, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_highway_st_peters_n.jpeg'],
  ['Princes Highway (St Peters S) · SYD MET', -33.907028, 151.181638, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_highway_st_peters_s.jpeg'],
  ['Princes Highway (Sutherland) · SYD SOUTH', -34.035113, 151.066129, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_highway_sutherland.jpeg'],
  ['Princes Highway (Wollongong) · REG SOUTH', -34.412822, 150.8926, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_highway_wollongong.jpeg'],
  ['Princes Highway (Albion Park Rail) · REG SOUTH', -34.55638, 150.791795, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_highway_and_airport_rd_albion_park_rail.jpeg'],
  ['Richmond Bridge (North Richmond) · SYD WEST', -33.58241, 150.722183, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/richmond_bridge_north_richmond.jpeg'],
  ['Rocky Point Rd and Captain Cook Bridge · SYD MET', -34.0046654, 151.128662, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/rocky_point_rd_on_the_captain_cook_bridge.jpeg'],
  ['Ryde Bridge (Ryde) · SYD NORTH', -33.82227, 151.09685, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/ryde_bridge_ryde.jpeg'],
  ['Ryde Road (Pymble) · SYD NORTH', -33.75077, 151.14731, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/ryde_road_pymble.jpeg'],
  ['Sackville ferry (South) · SYD WEST', -33.5028725, 150.876053, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/sackville_ferry_south.jpeg'],
  ['Sackville Rd and Tizzana Rd (Sackville) · SYD WEST', -33.502872, 150.876053, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/sackville_rd_and_tizzana_rd_sackville.jpeg'],
  ['Seven Hills Road (Seven Hills) · SYD WEST', -33.76812, 150.9429, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/seven_hills_road_seven_hills.jpeg'],
  ['Shellharbour Road (Warilla) · REG SOUTH', -34.552399, 150.859907, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/shellharbour_road_warilla.jpeg'],
  ['Silverwater Road (Silverwater) · SYD WEST', -33.84314, 151.043808, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/silverwater_road_silverwater.jpeg'],
  ['Southern Cross Drive (Eastlakes) · SYD MET', -33.93581, 151.207382, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/southern_cross_drive_eastlakes.jpeg'],
  ['Stewart Street (Eastwood) · SYD NORTH', -33.7965, 151.06529, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/stewart_street_eastwood.jpeg'],
  ['Syd Einfeld Drive (Bondi Junction) · SYD MET', -33.89104, 151.24969, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/syd_einfeld_drive_bondi_junction.jpeg'],
  ['Syd Einfeld Drive (Centennial Park) · SYD MET', -33.889715, 151.24183, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/syd_einfeld_drive_centennial_park.jpeg'],
  ['Sydney Harbour Bridge · SYD MET', -33.85106, 151.21152, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/sydney_harbour_bridge.jpeg'],
  ['The Grand Parade (Brighton-Le-Sands) · SYD MET', -33.9609, 151.15636, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/the_grand_parade_brighton-le-sands.jpeg'],
  ['Victoria Road (Gladesville) · SYD NORTH', -33.83002, 151.12679, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/victoria_road_gladesville.jpeg'],
  ['Victoria Road (Parramatta) · SYD WEST', -33.80866, 151.00533, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/victoria_road_parramatta.jpeg'],
  ['Warringah Freeway (North Sydney) · SYD NORTH', -33.83378, 151.2113, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/warringah_freeway_north_sydney.jpeg'],
  ['Warringah Road (Forestville) · SYD NORTH', -33.77139, 151.205215, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/warringah_road_forestville.jpeg'],
  ['Warringah Road (Frenchs Forest) · SYD NORTH', -33.75168, 151.22659, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/warringah_road_frenchs_forest.jpeg'],
  ['Waterfall Way at Newell Falls · REG NORTH', -30.394527, 152.745996, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/waterfall_way_at_newell_falls.jpeg'],
  ['Wattle Street (Ultimo) · SYD MET', -33.8791733, 151.1957, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/wattle_street_ultimo.jpeg'],
  ['Webbs Creek ferry (East) · SYD NORTH', -33.387923, 150.982507, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/webbs_creek_ferry_east.jpeg'],
  ['Webbs Creek ferry (West) · SYD NORTH', -33.386823, 150.978459, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/webbs_creek_ferry_west.jpeg'],
  ['Wentworth Avenue (Sydney) · SYD MET', -33.879791, 151.209067, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/wentworth_avenue_sydney.jpeg'],
  ['Anzac Bridge and West Tower · SYD MET', -33.86874, 151.184158, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/west_tower_anzac_br_looking_east.jpeg'],
  ['William Street (East Sydney) · SYD MET', -33.87375, 151.2126, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/william_street_east_sydney.jpeg'],
  ['Windsor Road Bridge North (Windsor) · SYD WEST', -33.604618, 150.823667, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/windsor_road_bridge_north_windsor.jpeg'],
  ['Wisemans ferry (North) · SYD NORTH', -33.3805542, 150.987717, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/wisemans_ferry_north.jpeg'],
  ['Wisemans Ferry (South) · SYD NORTH', -33.3785477, 150.990479, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/wisemans_ferry_south.jpeg'],
  ['Wisemans Ferry Road (Cattai) · SYD WEST', -33.556805, 150.908216, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/wisemans_ferry_road_cattai.jpeg'],
  ['Yarramundi Bridge (Agnes Banks) · SYD WEST', -33.614604, 150.699815, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/yarramundi_bridge_agnes_banks.jpeg'],
  ['Sturt Highway (Wagga Wagga) · REG SOUTH', -35.117242, 147.3564, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/sturt_highway_wagga_wagga.jpeg'],
  ['Princes Highway (Worrigee) · REG SOUTH', -34.87701, 150.604954, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_highway_worrigee.jpeg'],
  ['Great Western Highway (Blackheath) · REG WEST', -33.635541, 150.284874, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/great_western_highway_blackheath.jpeg'],
  ['Great Western Highway (Lithgow) · REG WEST', -33.481315, 150.13689, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/great_western_highway_lithgow.jpeg'],
  ['Pacific Highway (Tweed Heads) · REG NORTH', -28.225954, 153.556941, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/pacific_highway_tweed_heads.jpeg'],
  ['Pacific Highway (Coffs Harbour) · REG NORTH', -30.283807, 153.126775, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/pacific_highway_coffs_harbour.jpeg'],
  ['Brisbane Street (Tamworth) · REG NORTH', -31.090845, 150.928247, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/brisbane_street_tamworth.jpeg'],
  ['Bruxner Highway (Lismore) · REG NORTH', -28.81536, 153.286858, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/bruxner_highway_lismore.jpeg'],
  ['New England Highway (Singleton) · REG NORTH', -32.556617, 151.167612, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/new_england_highway_singleton.jpeg'],
  ['Princes Highway (Oak Flats) · REG SOUTH', -34.573361, 150.822319, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_highway_oak_flats.jpeg'],
  ['Hume Highway (Douglas Park) · REG SOUTH', -34.192605, 150.712089, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/hume_hwy_&_nepean_river_douglas_park.jpeg'],
  ['Berowra Waters Ferry (Berowra Waters) · SYD NORTH', -33.60050158398923, 151.12472817764223, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/berowra_waters_ferry.jpeg'],
  ['Berowra Waters Road (Berowra Waters) · SYD NORTH', -33.600519561107376, 151.12482338080446, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/berowra_waters_ferry_queue.jpeg'],
  ['Yarramundi Bridge (Thermal Image) · SYD WEST', -33.614467, 150.699855, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/yarramundi_bridge_agnes_banks_thermal_image.jpeg'],
  ['Windsor Road Bridge South (Windsor) · SYD WEST', -33.60191, 150.822224, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/windsor_road_bridge_south_windsor.jpeg'],
  ['Silverdale Road (Wallacia) · SYD WEST', -33.864967, 150.634627, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/silverdale_rd_wallacia.jpeg'],
  ['Argyle Street (Picton) · SYD WEST', -34.170969, 150.610485, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/argyle_st_picton.jpeg'],
  ['Burragorang Road West (Mount Hunter) · SYD SOUTH', -34.071616, 150.639717, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/burragorang_road_west_mount_hunter.jpeg'],
  ['Burragorang Road East (Mount Hunter) · SYD SOUTH', -34.071616, 150.639817, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/burragorang_road_east_mount_hunter.jpeg'],
  ['Princes Highway (Kirrawee) · SYD SOUTH', -34.032151, 151.073716, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/princes_hwy_kirrawee.jpeg'],
  ['M12 (Cecil Hills) · SYD WEST', -33.878199, 150.82634, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/elizabeth_drive_cecil_hills.jpeg'],
  ['M12 (Badgerys Creek) · SYD WEST', -33.8586696, 150.749291, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/m12_interchange_badgerys_creek.jpeg'],
  ['Mort Street (Lithgow) · REG WEST', -33.481061, 150.161391, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/mort_st_lithgow.jpeg'],
  ['York St and Margaret St (Sydney) · SYD MET', -33.865088, 151.205623, 'https://webcams.transport.nsw.gov.au/livetraffic-webcams/cameras/york_st_and_margaret_st_sydney.jpeg']
];
